const products = [
  {
    id: 1,
    name: "NPK Fertilizer",
    category: "Fertilizers",
    stock: "250 kg",
    price: 750,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 2,
    name: "Wheat Seeds",
    category: "Seeds",
    stock: "50 kg",
    price: 120,
    unit: "/kg",
    status: "Low Stock",
  },
  {
    id: 3,
    name: "Pesticide Spray",
    category: "Pesticides",
    stock: "100 bottles",
    price: 500,
    unit: "/bottle",
    status: "In Stock",
  },
  {
    id: 4,
    name: "Organic Manure",
    category: "Manure",
    stock: "200 kg",
    price: 300,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 5,
    name: "Hybrid Rice Seeds",
    category: "Seeds",
    stock: "40 kg",
    price: 200,
    unit: "/kg",
    status: "Low Stock",
  },
  {
    id: 6,
    name: "Potash Fertilizer",
    category: "Fertilizers",
    stock: "300 units",
    price: 700,
    unit: "/unit",
    status: "In Stock",
  },
  {
    id: 7,
    name: "Corn Seeds",
    category: "Seeds",
    stock: "80 kg",
    price: 150,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 8,
    name: "Herbicide Spray",
    category: "Pesticides",
    stock: "120 bottles",
    price: 550,
    unit: "/bottle",
    status: "In Stock",
  },
  {
    id: 9,
    name: "Compost Manure",
    category: "Manure",
    stock: "250 kg",
    price: 250,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 10,
    name: "Sunflower Seeds",
    category: "Seeds",
    stock: "30 kg",
    price: 180,
    unit: "/kg",
    status: "Low Stock",
  },
  {
    id: 11,
    name: "Calcium Nitrate Fertilizer",
    category: "Fertilizers",
    stock: "150 units",
    price: 850,
    unit: "/unit",
    status: "In Stock",
  },
  {
    id: 12,
    name: "Soybean Seeds",
    category: "Seeds",
    stock: "60 kg",
    price: 200,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 13,
    name: "Insecticide Spray",
    category: "Pesticides",
    stock: "90 bottles",
    price: 600,
    unit: "/bottle",
    status: "In Stock",
  },
  {
    id: 14,
    name: "Cattle Manure",
    category: "Manure",
    stock: "180 kg",
    price: 280,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 15,
    name: "Cotton Seeds",
    category: "Seeds",
    stock: "70 kg",
    price: 160,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 16,
    name: "DAP Fertilizer",
    category: "Fertilizers",
    stock: "220 units",
    price: 800,
    unit: "/unit",
    status: "In Stock",
  },
  {
    id: 17,
    name: "Vegetable Seeds Pack",
    category: "Seeds",
    stock: "100 packs",
    price: 90,
    unit: "/pack",
    status: "In Stock",
  },
  {
    id: 18,
    name: "Fungicide Powder",
    category: "Pesticides",
    stock: "70 packets",
    price: 350,
    unit: "/packet",
    status: "Low Stock",
  },
  {
    id: 19,
    name: "Vermicompost",
    category: "Manure",
    stock: "160 kg",
    price: 400,
    unit: "/kg",
    status: "In Stock",
  },
  {
    id: 20,
    name: "Barley Seeds",
    category: "Seeds",
    stock: "50 kg",
    price: 140,
    unit: "/kg",
    status: "Low Stock",
  },
];

export default products;
